AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: DynamoDb.


Resources:
##########################################################################
#  DynamoDB                                                              #
##########################################################################
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

Outputs:
  DynamodbTableName:
    Description: "DynamoDB table Name"
    Value: !Ref Table
    Export:
      Name: DynamodbTableName
  DynamodbTableArn:
    Description: "DynamoDB table ARN"
    Value: !GetAtt Table.Arn
    Export:
      Name: DynamodbTableArn