AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: DynamoDb.


Resources:
##########################################################################
#  DynamoDB                                                              #
##########################################################################
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  StreamingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

Outputs:
  DeviceTableName:
    Description: "DynamoDB Device Table Name"
    Value: !Ref DeviceTable
    Export:
      Name: DeviceTableName
  DeviceTableArn:
    Description: "DynamoDB Device Table ARN"
    Value: !GetAtt DeviceTable.Arn
    Export:
      Name: DeviceTableArn
  StreamingTableeName:
    Description: "DynamoDB Streaming Table Name"
    Value: !Ref StreamingTable
    Export:
      Name: StreamingTableName
  StreamingTableArn:
    Description: "DynamoDB Streaming Table ARN"
    Value: !GetAtt StreamingTable.Arn
    Export:
      Name: StreamingTableArn