AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: DynamoDb.


Resources:
##########################################################################
#  DynamoDB                                                              #
##########################################################################
  SubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  StreamingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: ttlExpireAt
        Enabled: true
      BillingMode: PAY_PER_REQUEST

Outputs:
  SubscriptionTableName:
    Description: "DynamoDB Device Table Name"
    Value: !Ref SubscriptionTable
    Export:
      Name: SubscriptionTableName
  SubscriptionTableArn:
    Description: "DynamoDB Device Table ARN"
    Value: !GetAtt SubscriptionTable.Arn
    Export:
      Name: SubscriptionTableArn
  StreamingTableeName:
    Description: "DynamoDB Streaming Table Name"
    Value: !Ref StreamingTable
    Export:
      Name: StreamingTableName
  StreamingTableArn:
    Description: "DynamoDB Streaming Table ARN"
    Value: !GetAtt StreamingTable.Arn
    Export:
      Name: StreamingTableArn