AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon API Gateway HTTP API and an AWS Lambda function.

##########################################################################
#  Parameters                                                            #
##########################################################################
Parameters:
  VpcId:
    Description: VPC where the APIGW will be created
    Type: String
  StageName:
    Description: The name of the stage is the first path segment in the Uniform Resource Identifier (URI) of a call to API Gateway
    Type: String
    Default: dev

##########################################################################
#  Global values that are applied to all resources                       #
##########################################################################
Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 29
    Environment:
      Variables:
        RUST_BACKTRACE: 1
        RUST_LOG: info

Resources:

##########################################################################
#  API Gateway REST API                                                  #
##########################################################################
  StreamApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Name: !Ref AWS::StackName
      Description: An Amazon private REST API Gateway and an AWS Lambda function.
      Models:
        Input:
          type: object
          required:
            - user_id
            - video_id
          properties:
            user_id:
              type: string
            video_id:
              type: string
      # EndpointConfiguration:
      #   Type: PRIVATE
      #   VPCEndpointIds: 
      #     - !Ref VpcId
      Auth:
        ResourcePolicy:
          CustomStatements: [{
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "execute-api:/*/*/*"
          }]

##########################################################################
#   Lambda Function                                                      #
##########################################################################
  StreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/stream
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:PutItem
              Resource: 
                - !ImportValue StreamingTableArn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !ImportValue SubscriptionTableArn
      Environment:
        Variables:
          STREAMING_TABLE_NAME: !ImportValue StreamingTableName
          SUBSCRIPTION_TABLE_NAME: !ImportValue SubscriptionTableName
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /stream
            Method: POST
            RestApiId: !Ref StreamApi

Outputs:
  HttpApiEndpoint:
    Description: The Stream endpoint.
    Value: !Sub "https://${StreamApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"