AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: EventBridge 

Resources:
##########################################################################
#   EventBridge                                                          #
##########################################################################
  S3PresignedUrlBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref AWS::StackName

Outputs:
  S3PresignedUrlBusName:
    Description: EventBridge s3 pre signed url bus name
    Value: !Ref S3PresignedUrlBus
    Export:
      Name: S3PresignedUrlBusName
  S3PresignedUrlBusArn:
    Description: EventBridge s3 pre signed url bus arn
    Value: !GetAtt S3PresignedUrlBus.Arn
    Export:
      Name: S3PresignedUrlBusArn
