AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventBridge to Lambda

# Global values that are applied to all applicable resources in this template
Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 29
    Environment:
      Variables:
        RUST_BACKTRACE: 1
        RUST_LOG: info

Resources:
##########################################################################
#   Lambda Function                                                      #
##########################################################################

  S3PresignedUrlLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/s3-presigned-url/
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:PutObject"
              Resource:
                - !ImportValue SourceBucketArn
                - !Sub
                  - "${SourceBucketArn}/*"
                  - SourceBucketArn: !ImportValue SourceBucketArn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !ImportValue WebSocketPostArn
      Environment:
        Variables:
          BUCKET_NAME: !ImportValue SourceBucket
          WSS_DOMAIN: !ImportValue WebSocketDomain
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: !ImportValue S3PresignedUrlBusName
            Pattern:
              source:
                - doorbell.onconnect
              detail-type:
                - "connected"

Outputs:
  S3PresignedUrlLambdaFunction:
    Description: "S3PresignedUrl function ARN"
    Value: !GetAtt S3PresignedUrlLambdaFunction.Arn