AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: StepFunctions state machine

# Global values that are applied to all applicable resources in this template
Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 29
    Environment:
      Variables:
        RUST_BACKTRACE: 1
        RUST_LOG: info

Resources:
##########################################################################
#   STEP FUNCTION                                                        #
##########################################################################
  CompareFaceStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/stateMachine.asl.json
      DefinitionSubstitutions:
        GenerateCodeFunctionArn: !GetAtt GenerateCodeFunction.Arn
        SendCodeFunctionArn: !GetAtt SendCodeFunction.Arn
        SendPhotoToMobileArn: !GetAtt SendPhotoToMobile.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "cloudwatch:*"
                - "logs:*"
                - "rekognition:CompareFaces"
              Resource: "*"
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: 
                - !GetAtt GenerateCodeFunction.Arn
                - !GetAtt SendCodeFunction.Arn
                - !GetAtt SendPhotoToMobile.Arn
            - Effect: Allow
              Action:
                - "s3:GetObject"
              Resource:
                - !Sub
                  - "${SourceBucketArn}/*"
                  - SourceBucketArn: !ImportValue SourceBucketArn
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt CompareFaceStateMachineLogGroup.Arn
        IncludeExecutionData: false
        Level: 'ALL'
      Events:
        StateChange:
          Type: EventBridgeRule
          Properties:
            InputPath: $.detail
            Pattern:
              source:
                - aws.s3
              detail:
                bucket:
                  name: 
                    - !ImportValue SourceBucket
                object:
                  key: 
                    - prefix: 'guest/'
                reason:
                  - PutObject

##########################################################################
#  STEP FUNCTION LOG GROUP                                               #
##########################################################################
  CompareFaceStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "/", [ "stepfunctions", CompareFaceStateMachine]]

##########################################################################
#   Lambda Function                                                      #
##########################################################################

  GenerateCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/generate-code/
      Policies:
        - AWSLambdaBasicExecutionRole
  
  SendCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/send-code/
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
##########################################################################
# this is wrong we should push to the mobile app not to the doorbell
# this is here only to simulate and facilitate testing
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections" 
              Resource:
                - !ImportValue WebSocketPostArn
      Environment:
        Variables:
          WSS_DOMAIN: !ImportValue WebSocketDomain 
##########################################################################

  SendPhotoToMobile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/send-photo/
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:GetObject"
              Resource:
                - !ImportValue SourceBucketArn
                - !Sub
                  - "${SourceBucketArn}/*"
                  - SourceBucketArn: !ImportValue SourceBucketArn
##########################################################################
# this is wrong we should push to the mobile app not to the doorbell
# this is here only to simulate and facilitate testing
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections" 
              Resource:
                - !ImportValue WebSocketPostArn
      Environment:
        Variables:
          BUCKET_NAME: !ImportValue SourceBucket
          WSS_DOMAIN: !ImportValue WebSocketDomain 
##########################################################################

Outputs:
  CompareFaceStateMachine:
    Value: !Ref CompareFaceStateMachine
    Description: CompareFaceStateMachine Arn
