AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3 Bucket to store the photos

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteLifeCyclePolicy
            Status: Enabled
            ExpirationInDays: 1

Outputs:
  SourceBucketName:
    Value: !Ref SourceBucket
    Export:
      Name: SourceBucket
  SourceBucketArn:
      Value: !GetAtt: SourceBucket.Arn
      Export:
        Name: SourceBucketArn
