AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EventBridge to Lambda

# Global values that are applied to all applicable resources in this template
Globals:
  Function:
    MemorySize: 1024
    Architectures: ["arm64"]
    Handler: bootstrap
    Runtime: provided.al2
    Timeout: 29
    Environment:
      Variables:
        RUST_BACKTRACE: 1
        RUST_LOG: info

Resources:
##########################################################################
#   EventBridge                                                          #
##########################################################################
  S3PresignedUrlBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref AWS::StackName

  #EventBridge rules and permissions
  EventRuleInsert:
    Type: AWS::Events::Rule
    Properties:
      Description: "Insert transactions"
      EventBusName: !GetAtt S3PresignedUrlBus.Arn
      EventPattern:
        source:
          - "doorbell.onconnect"
        detail-type:
          - connected
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt S3PresignedUrlLambdaFunction.Arn
          Id: "eventRuleInsert"

##########################################################################
#   Lambda Function                                                      #
##########################################################################
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: S3PresignedUrlLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventRuleInsert.Arn

  S3PresignedUrlLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../build/s3-presigned-url/
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:PutObject"
              Resource:
                - !ImportValue SourceBucketArn
      Environment:
        Variables:
          TABLE_NAME: !ImportValue SourceBucket
      # Events:
      #   Trigger:
      #     Type: EventBridgeRule
      #     EventBusName: !Ref S3PresignedUrlBus
      #     Properties:
      #       Pattern:
      #         source:
      #           - doorbell.onconnect
      #         detail-type:
      #           - "connected"

Outputs:
  S3PresignedUrlBusName:
    Description: EventBridge s3 pre signed url bus name
    Value: !Ref S3PresignedUrlBus
    Export:
      Name: S3PresignedUrlBusName
  S3PresignedUrlBusArn:
    Description: EventBridge s3 pre signed url bus arn
    Value: !GetAtt S3PresignedUrlBus.Arn
    Export:
      Name: S3PresignedUrlBusArn